function CheckUnsaved(CurTaskParameters, SavedTaskParameters,...
                      SettingsPath, BpodSystem)
changes = '';
if isempty(fieldnames(SavedTaskParameters))
    changes = ['(Whole configuration is not saved. '...
               'Probably first time to run this setting?)'];
else
    fields_names = fieldnames(CurTaskParameters.GUI);
    for n=1:length(fields_names)
        field_name = fields_names{n};
        if isequal(field_name, 'GUIVer')
            continue
        elseif isfield(CurTaskParameters.GUI,field_name) && ...
          ~isfield(SavedTaskParameters.GUI, field_name)
            changes = [changes, ' \\bf ', field_name, ' \\rm',...
                ' - Exists only in new configuration. ',...
                'Maybe Software was updated?\n'];
        elseif (~isfield(CurTaskParameters.GUIMeta,field_name) || ...
          ~isfield(CurTaskParameters.GUIMeta.(field_name),'Style') || ...
          ~strcmp(CurTaskParameters.GUIMeta.(field_name).Style,'text')) ...
          && ~isequal(CurTaskParameters.GUI.(field_name), ...
                      SavedTaskParameters.GUI.(field_name))
            toStr = @mat2str;
            if isstruct(CurTaskParameters.GUI.(field_name))
                toStr = @(field_value) '(sub-value changed)';
            elseif isfield(CurTaskParameters.GUIMeta,field_name) && ...
             isfield(CurTaskParameters.GUIMeta.(field_name),'Style') && ...
             strcmp(CurTaskParameters.GUIMeta.(field_name).Style,'checkbox')
                toStr = @(is_chked)(iff(is_chked,'box checked',...
                                                 'box unchecked'));
            end
            changes = [changes, ' \\bf', field_name, ...
                ' \\rm \\it - Unsaved: \\rm ',...
                toStr(CurTaskParameters.GUI.(field_name)), ...
                ' - \\it saved: ', toStr(...
                SavedTaskParameters.GUI.(field_name)), '\n'];
        end
    end
end
if ~isempty(changes)
    msg = ['\\fontsize{12}Current settings are not ',...
           'saved. Changes are:\n', changes];
    Opt.Interpreter = 'tex';
    Opt.Default = 'Save';
    answer = questdlg(sprintf(msg), 'Unsaved settings detected',...
        'Quit without saving', 'Save','Save as...', Opt);
    if strcmp(answer, 'Save')
        save(SettingsPath,'CurTaskParameters')
    elseif strcmp(answer, 'Save as...')
        [file,path] = uiputfile('*.mat',...
                                'Select a Bpod ProtocolSettings file.',...
                                SettingsPath);
        if file>0
            save(fullfile(path,file),'CurTaskParameters')
        end
    end
end
end

